version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: lunch_decision_db
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
